package com.example.posdummy.vo;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "sales")
public class Sales {

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @Column(name = "sales_id")
    private long salesId;

    @Column(name = "customer_name",columnDefinition = "VARCHAR DEFAULT Walk-in-Customer")
    private String customerName;

    @Column(name = "order_no")
    private String orderNo; //prefix  + sequence No (autogenerated)

    private LocalDateTime date;




}
